name: Deploy to GitHub Pages

on:
  push:
    branches:
      - GitPagesOnline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Publish .NET Project
      run: dotnet publish -c Release -o release

    - name: Adjust base href
      run: sed -i 's|<base href="/" />|<base href="/Main/" />|g' release/wwwroot/index.html

    - name: Create .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot